name: Node.js CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  server-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Server Dependencies
      run: |
        cd server
        npm install -g npm@latest
        npm ci

    - name: Run Server Tests
      run: |
        cd server
        npm test
